apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Swamp
metadata:
  name: manager-controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  depth: 10


